baseURL = "https://ph-yrittajalehti.fi/"
languageCode = "fi"
title = "PH-Yrittäjälehti"
theme = "Blogpaper"
summaryLenght = 100


[menu]

  [[menu.main]]
  name = "Yhteys"
  identifier = "yhteys"
  weight = 300
  url = "/yhteys/"
